model = "gpt-5-codex"
model_reasoning_effort = "medium"
hide_agent_reasoning = true
network_access = true

sandbox_mode = "read-only"
approval_policy = "untrusted"

file_opener = "vscode"
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[tools]
web_search = true

